name: Deploy GAS to DEV or PROD by Branch

# ワークフローが実行されるトリガーを設定
on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'kotaete-web/gas/**'

jobs:
  deploy-gas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install clasp
        run: npm install -g @google/clasp

      # --- ブランチに応じて .clasp.json を動的に生成 ---
      - name: Create .clasp.json for PROD
        if: github.ref == 'refs/heads/main'
        run: |
          echo "{\"scriptId\":\"${{ secrets.PROD_SCRIPT_ID }}\",\"rootDir\":\"./kotaete-web/gas\"}" > .clasp.json
          echo "Target: PROD environment"

      - name: Create .clasp.json for DEV
        if: github.ref == 'refs/heads/develop'
        run: |
          echo "{\"scriptId\":\"${{ secrets.DEV_SCRIPT_ID }}\",\"rootDir\":\"./kotaete-web/gas\"}" > .clasp.json
          echo "Target: DEV environment"

      # --- 認証用 clasprc.json を secrets から復元 (Base64デコード) ---
      # 重要: CLASPRC_JSON_RAW には、clasp login で取得した認証情報JSONを Base64 エンコードした文字列を設定してください。
      # ローカルで `cat ~/.clasprc.json | base64` を実行して得られる文字列です。
      - name: Create .clasprc.json from Base64 secret
        run: |
          echo '${{ secrets.CLASPRC_JSON_RAW }}' | base64 --decode > ~/.clasprc.json
          echo ".clasprc.json was created from secret." # ファイル作成の確認メッセージ
          # !!! 注意 !!!
          # 以下のコマンドは、機密情報である .clasprc.json の内容の一部をログに出力します。
          # デバッグ目的以外では使用せず、デバッグ完了後は必ず削除してください。
          echo "--- .clasprc.json content (first 50 chars) for debug ---"
          head -c 50 ~/.clasprc.json
          echo "--- End of .clasprc.json debug ---"


      # --- clasp 実行 ---
      - name: Push files to Google Apps Script
        run: clasp push -f

      - name: Deploy to the target environment
        run: clasp deploy --description "Auto-deployment from branch ${{ github.ref_name }}"
